{
  activity: 'GP-Lig-Activity-Service-dev',
  adminAPI: 'GP-Lig-Admin-API-dev',
  badge: 'GP-Lig-Badge-Service-dev',
  championships: 'GP-Lig-Championship-Service-dev',
  game: 'GP-Lig-Game-Service-dev',
  leaderboard: 'GP-Lig-Leaderboard-Service-dev',
  league: 'GP-Lig-League-Service-dev',
  mobileAPI: 'GP-Lig-Mobile-API-dev',
  notification: 'GP-Lig-Notification-Service-dev',
  orchestrator: 'GP-Lig-Orchestrator-Service-dev',
  scoreHistory: 'GP-Lig-Score-History-Service-dev',
  tournaments: 'GP-Lig-Tournament-Service-dev',
  user: 'GP-Lig-User-Service-dev',
  iap: 'GP-Lig-IAP-Service-dev',
}
