apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: new-relic
  namespace: lig
spec:
  encryptedData:
    NR_API_KEY: AgBRUal3CcfISsgZ+DbgTF82IRUIwYxNUzgWaR5tyV0AZREISM+bVBEwis1LJXuxDIJ7kB8ngA32fpCoBOnp1Ui9Fm58EQaQn2nwmdVESdyEZuDK5z4VQR0VulQh383TUli810e4eHs93Dsuj26arFxi+V/6WqchVj/VnyzI+i8XH3cNys/LDqqkgplmsc/XhvugNRP01nGLO86ny4JXE4mB4E7jABKyD/+PWg4/sApPhuwDpBVMADZyU/0xCDZzD4VkqRT9wpqOsEWlhEvU6d76upsgPu+MLgwBHVmF1wmppXcyVSJ2EsuYjqgXJAa0hbjjuvpwBrLBvkoyYZ1n6JwXa1EQaa2eFSFF4e9DilQC3DJDjFbLOf2rbkekMGsFw5wRv9gOBcy6GvTzY5iX6mDHxG0nBNB7jMzxkBBFD7d95eIpOdidRiCotzgh6cRjmj5RlKUN2PxwYEA1w4rT1nrIfjzh1t+WgdQS2bDwM7m0dPRxNwTAyhWshu9jMepvl/RQxv79njnOYYcyvhyhSCCSnSmSiCxjQYFWbEMzzRqf90Yd2gnEQeNwFhH7KvrKKRJ9Q4NZCTD7vSmnUb01T9YjuIAVctmF6gUvAmrk44x1UJLz57y31KkwB5a1k6cdvkQst+nb+7tBneF2ze1fH1S3ylk6vEh9zsFrOEcuQR9J57mLJXCUOipOM2PtagtMjtb6KvnInE7rdPRbTClYZusyKVe9NctEiS0YAfGEs6zDFSkvXaV9AmWi
  template:
      name: new-relic
      namespace: lig

