apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-notification
  namespace: lig
spec:
  encryptedData:
    AWS_SNS_ANDROID: AgB484ERsal/VVmY8GMb0NQV7kQ8EVwna2mBHYjndy0qeiuGa2WKo1ydx/u8ocyBkpIfLywz4h0klVLwVK+XrTXLO3pcvWHpclPTbUXv6K06gYmLnnYsyEoeuDQH5FTzwmo+xgo5CliEolZ4Eabkxcq+5A7gsm7XsIi4IZHCIZjKUHzVP/mohSHRtz065m11Tk1SieWzvyGIJEVpN3RWj1H18kZK7N7wdJWky2DKkrWRoMmaVEFnzGoqDmN88f7W7C8GPSIg6+Kszo9hBIiE9BiKqXjw8PJa5nZE6Iwyp2W149AcRUd7Re1+qnP5Zngg3jC7mIJOgkakn4d/ItFNPW9af0ZL3rY+kx1cP/4X1LX2luenIoKkZpGYMMcC3RpfdAU/SPTWii0rKFLVl+vGgUcEcngeD9aDrkPZy5soTnFtj+4oWHEBsm6EFt3WIMo8L6e+lele+OfA8rsdNl+4Q1KQDsBSDGXCivzPOvVrXlfysedriVGIJJnk5X14PRiakfRHZBaG1BZaF2fSEue+C4lgOQbBDmvupPJNKk1uft8LiRMHYV0RdG8KFfE15BVBrhy1bpnc9FLcb3OEyx9/cx0mtmU6TrtQ5htOBtHeKR01COUPoptwZNalz/gktVF7qfGyqqkgUSM3k9Z2GUZT669GlWewWuGjKSJmZFdtvE5PyvnARTwxZt96gzMVUpY8+PgXzzKt40QNkuanE5did6ISsC/dQiflMMBe2b7oE1jmHQv7x7RGUYEJuzrVK6hQWU/SHl+Pz/lf6Xbh
  template:
    metadata:
      name: app-notification
      namespace: lig

